#!/usr/bin/env python3
"""Build the static, CSP-clean website for AGSSH-STD-001 (published at agssh.dev).

The site is a purpose-built WEB surface, distinct from the print PDF: it carries
NO inline <style>/<script> and NO inline style="" attributes, so a strict CSP
(default-src 'none'; style-src 'self'; img-src 'self'; everything else 'none')
holds — which is exactly what lets the page pass agssh's own AG-NET-01 / AG-CSP-02
at Gold. All styling lives in one same-origin stylesheet; all assets are
first-party. The dogfood: the site that publishes the standard conforms to it.

Inputs (already generated by build_pdf.py — run that first):
  ../RULES.md                          the rule table (id/title/oblig/sev/profile/levels)
  ../internal/rules/version_gen.go     the version constant
  AGSSH-STD-001-<ver>.pdf              the rendered standard (copied into the site)

Outputs (into ../site/):
  index.html  agssh-std.css  AGSSH-STD-001-<ver>.pdf  (badge.svg is added by CI)
"""
import os
import re
import html
import shutil

_here = os.path.dirname(os.path.abspath(__file__))
_root = os.path.join(_here, "..")
_site = os.path.join(_root, "site")


def version():
    vg = open(os.path.join(_root, "internal", "rules", "version_gen.go")).read()
    m = re.search(r'StandardVersion = "([^"]+)"', vg)
    if not m:
        raise SystemExit("build_site: cannot read StandardVersion from version_gen.go")
    return m.group(1)


def parse_rules():
    """Parse RULES.md into [(family_id, family_title, [rows])]; row = dict."""
    md = open(os.path.join(_root, "RULES.md")).read()
    fams, cur = [], None
    for line in md.splitlines():
        h = re.match(r"^## §\S+\s+(AG-[A-Z]+)\s+—\s+(.+?)\s*$", line)
        if h:
            cur = (h.group(1), h.group(2), [])
            fams.append(cur)
            continue
        r = re.match(r"^\|\s*`(AG-[A-Z0-9a-z-]+)`\s*\|(.+)$", line)
        if r and cur is not None:
            cells = [c.strip().replace("\\|", "|") for c in r.group(2).split("|")]
            # cells: title, oblig, severity, profile, levels (trailing empty from |)
            title, oblig, sev, prof, levels = (cells + ["", "", "", "", ""])[:5]
            cur[2].append(dict(id=r.group(1), title=title, oblig=oblig,
                               sev=sev, prof=prof, levels=levels))
    return fams


def esc(s):
    return html.escape(s, quote=True)


CSS = """\
/* AGSSH-STD-001 — agssh.dev. One same-origin stylesheet; system fonts only, so
   font-src can be 'none'. No @import, no url() to any third party. */
:root {
  --ink:#0f172a; --muted:#64748b; --line:#e2e8f0; --bg:#ffffff; --soft:#f8fafc;
  --blue:#2563eb; --bronze:#b45309; --silver:#475569; --gold:#a16207;
  --crit:#b91c1c; --high:#c2410c; --med:#b45309; --low:#475569;
  --mono:ui-monospace,"SF Mono","DejaVu Sans Mono",Menlo,Consolas,monospace;
  --sans:system-ui,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
}
* { box-sizing:border-box; }
html { -webkit-text-size-adjust:100%; }
body { margin:0; font-family:var(--sans); color:var(--ink); background:var(--bg);
       line-height:1.55; font-size:16px; }
a { color:var(--blue); text-decoration:none; }
a:hover { text-decoration:underline; }
code { font-family:var(--mono); font-size:.88em; background:var(--soft);
       border:1px solid var(--line); border-radius:4px; padding:1px 5px; }
.wrap { max-width:960px; margin:0 auto; padding:0 20px; }

header.hero { background:var(--ink); color:#e2e8f0; padding:48px 0 40px;
              border-bottom:4px solid var(--blue); }
.hero .eyebrow { font-size:12px; letter-spacing:3px; font-weight:700;
                 color:#93c5fd; text-transform:uppercase; }
.hero h1 { margin:6px 0 4px; font-size:40px; letter-spacing:-.5px; color:#fff; }
.hero .tag { font-size:18px; color:#cbd5e1; margin:0 0 20px; max-width:60ch; }
.hero .meta { font-size:13px; color:#94a3b8; }
.hero .meta b { color:#e2e8f0; }
.badge-wrap { margin:20px 0 4px; }
.badge-wrap img { height:40px; width:auto; }

main { padding:44px 0 8px; }
h2 { font-size:22px; margin:40px 0 12px; padding-bottom:6px;
     border-bottom:2px solid var(--blue); scroll-margin-top:16px; }
h3 { font-size:16px; margin:26px 0 8px; }
p { margin:12px 0; }
.lead { font-size:17px; color:#334155; }

.cards { display:grid; grid-template-columns:repeat(auto-fit,minmax(200px,1fr));
         gap:14px; margin:20px 0; }
.card { border:1px solid var(--line); border-radius:8px; padding:14px 16px;
        background:var(--soft); }
.card .k { font-size:12px; letter-spacing:.5px; text-transform:uppercase;
           color:var(--muted); font-weight:700; }
.card .v { font-size:15px; margin-top:4px; }

.toc { display:flex; flex-wrap:wrap; gap:8px; margin:16px 0; padding:0; list-style:none; }
.toc a { border:1px solid var(--line); border-radius:999px; padding:4px 12px;
         font-size:13px; font-family:var(--mono); background:var(--soft); }

table { width:100%; border-collapse:collapse; margin:10px 0 24px; font-size:14px; }
th, td { text-align:left; padding:8px 10px; border-bottom:1px solid var(--line);
         vertical-align:top; }
th { font-size:12px; text-transform:uppercase; letter-spacing:.4px;
     color:var(--muted); background:var(--soft); }
td.id code { background:transparent; border:0; padding:0; color:var(--blue);
             font-weight:600; }
.tablewrap { overflow-x:auto; }

.chip { display:inline-block; font-size:11px; font-weight:700; letter-spacing:.3px;
        padding:2px 8px; border-radius:999px; border:1px solid; white-space:nowrap; }
.sev-CRITICAL { color:var(--crit); border-color:var(--crit); }
.sev-HIGH { color:var(--high); border-color:var(--high); }
.sev-MEDIUM { color:var(--med); border-color:var(--med); }
.sev-LOW { color:var(--low); border-color:var(--low); }
.prof-Bronze { color:var(--bronze); border-color:var(--bronze); }
.prof-Silver { color:var(--silver); border-color:var(--silver); }
.prof-Gold { color:var(--gold); border-color:var(--gold); }
.must { font-weight:700; color:var(--ink); }
.should { color:var(--muted); }

.proof { border:1px solid var(--line); border-left:4px solid var(--blue);
         border-radius:8px; background:var(--soft); padding:16px 18px; margin:28px 0; }
.proof h3 { margin:0 0 6px; }

footer { border-top:1px solid var(--line); margin-top:40px; padding:28px 0 48px;
         color:var(--muted); font-size:14px; }
footer a { color:var(--muted); text-decoration:underline; }

@media (max-width:560px){ .hero h1{font-size:30px;} body{font-size:15px;} }
@media (prefers-color-scheme:dark){
  :root{ --ink:#e2e8f0; --muted:#94a3b8; --line:#334155; --bg:#0b1120; --soft:#111827; }
  header.hero{ background:#060a14; }
  code{ color:#e2e8f0; }
}
"""


FAVICON = """\
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
  <path d="M16 2 4 7v9c0 7.5 5.1 12.2 12 14 6.9-1.8 12-6.5 12-14V7L16 2z" fill="#2563eb"/>
  <path d="M22 12.5l-7.6 7.6L10 15.7l1.8-1.8 2.6 2.6 5.8-5.8 1.8 1.8z" fill="#fff"/>
</svg>
"""

# Neutral placeholder — NO tier claim. The gate overwrites this with the real,
# scan-derived medal once agssh.dev actually earns it.
PLACEHOLDER_BADGE = """\
<svg xmlns="http://www.w3.org/2000/svg" width="150" height="40" role="img" aria-label="AGSSH-STD-001 — self-verifying">
  <rect width="150" height="40" rx="6" fill="#0f172a"/>
  <text x="12" y="17" font-family="Verdana,sans-serif" font-size="11" fill="#e2e8f0" font-weight="bold">AGSSH-STD-001</text>
  <text x="12" y="30" font-family="Verdana,sans-serif" font-size="9" fill="#93c5fd">self-verifying…</text>
</svg>
"""

PENDING_JSON = ('{\n  "status": "pending",\n  "note": "This %s is produced by the '
                'publish-standard workflow scanning the live agssh.dev at Gold, and '
                'replaces this placeholder after the first successful gate."\n}\n')


def rules_section(fams):
    out = ['<h2 id="rules">The 57 rules</h2>',
           '<p class="lead">Nine families, three cumulative profiles '
           '(<span class="chip prof-Bronze">Bronze</span> ⊂ '
           '<span class="chip prof-Silver">Silver</span> ⊂ '
           '<span class="chip prof-Gold">Gold</span>), three strictness levels '
           '(L0 strict air-gap · L1 scoped egress · L2 marketing). '
           'Full normative text is in the <a href="%s">PDF</a>.</p>' % PDF_NAME]
    out.append('<ul class="toc">')
    for fid, ftitle, rows in fams:
        out.append('<li><a href="#%s">%s</a></li>' % (fid.lower(), esc(fid)))
    out.append('</ul>')
    for fid, ftitle, rows in fams:
        out.append('<h3 id="%s">%s — %s</h3>' % (fid.lower(), esc(fid), esc(ftitle)))
        out.append('<div class="tablewrap"><table><thead><tr>'
                   '<th>Rule</th><th>Requirement</th><th>Obl.</th>'
                   '<th>Severity</th><th>Profile</th><th>Levels</th></tr></thead><tbody>')
        for r in rows:
            ob = ('<span class="must">MUST</span>' if r["oblig"] == "MUST"
                  else '<span class="should">SHOULD</span>')
            out.append(
                '<tr><td class="id"><code>%s</code></td><td>%s</td><td>%s</td>'
                '<td><span class="chip sev-%s">%s</span></td>'
                '<td><span class="chip prof-%s">%s</span></td>'
                '<td>%s</td></tr>' % (
                    esc(r["id"]), esc(r["title"]), ob,
                    esc(r["sev"]), esc(r["sev"]), esc(r["prof"]), esc(r["prof"]),
                    esc(r["levels"])))
        out.append('</tbody></table></div>')
    return "\n".join(out)


def build():
    ver = version()
    global PDF_NAME
    PDF_NAME = "AGSSH-STD-001-%s.pdf" % ver
    fams = parse_rules()
    n_rules = sum(len(r) for _, _, r in fams)
    n_fam = len(fams)

    doc = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="AGSSH-STD-001 — the Air-Gapped Static Surface Hardening standard. {n} property-based, fail-closed conformance rules for static and client-side web surfaces.">
<meta name="color-scheme" content="light dark">
<title>AGSSH-STD-001 — Air-Gapped Static Surface Hardening</title>
<link rel="icon" href="favicon.svg" type="image/svg+xml">
<link rel="stylesheet" href="agssh-std.css">
</head>
<body>
<header class="hero"><div class="wrap">
  <div class="eyebrow">Deterministic Security Standard</div>
  <h1>AGSSH-STD-001</h1>
  <p class="tag">The Air-Gapped Static Surface Hardening standard — {n} property-based,
  fail-closed conformance rules that prove a static or client-side surface talks only
  to its own origin.</p>
  <div class="badge-wrap"><img src="badge.svg" alt="AGSSH conformance badge for this site" width="150" height="40"></div>
  <div class="meta"><b>{ver}</b> &nbsp;·&nbsp; {n} rules · {f} families · Bronze / Silver / Gold ·
  <a href="{pdf}">PDF</a> · <a href="https://github.com/fabriziosalmi/agssh">runner &amp; source</a></div>
</div></header>

<main class="wrap">
  <p class="lead">A <em>surface</em> — a client-side tool, a docs site, a marketing page —
  should talk only to its own origin. AGSSH-STD-001 pins that property down as {n} testable
  rules, and <a href="https://github.com/fabriziosalmi/agssh"><code>agssh</code></a> is the
  deterministic, fail-closed runner that enforces them against the <em>live</em> deployment.</p>

  <div class="cards">
    <div class="card"><div class="k">Profiles</div><div class="v">Bronze &#8834; Silver &#8834; Gold, cumulative</div></div>
    <div class="card"><div class="k">Levels</div><div class="v">L0 strict &middot; L1 scoped &middot; L2 marketing</div></div>
    <div class="card"><div class="k">Posture</div><div class="v">Fail-closed — nothing is green unless proven</div></div>
    <div class="card"><div class="k">Evidence</div><div class="v">Externally derived, signed conformance record</div></div>
  </div>

  <div class="proof">
    <h3>This page eats its own dog food.</h3>
    <p>agssh.dev is a static surface published behind Cloudflare, and it passes AGSSH-STD-001
    at its highest bar. The badge above is generated by <code>agssh</code> scanning this very
    site — a fail-closed claim that reproduces from the
    <a href="conformance.json">signed conformance record</a> (and its
    <a href="sbom.spdx.json">SBOM</a>). The standard that says "prove it" proves it.</p>
  </div>

{rules}

  <h2 id="run">Run it yourself</h2>
  <p>Point the runner at any live URL and read the verdict — no build step:</p>
  <div class="tablewrap"><table><tbody>
    <tr><td class="id"><code>go install github.com/fabriziosalmi/agssh/cmd/agssh@latest</code></td></tr>
    <tr><td class="id"><code>agssh -config .airgap.yml -profile Gold</code></td></tr>
  </tbody></table></div>
  <p>See the <a href="https://github.com/fabriziosalmi/agssh#readme">README</a> for the GitHub Action
  and MCP-server entry points, and <a href="{pdf}">the PDF</a> for the full normative text.</p>
</main>

<footer><div class="wrap">
  AGSSH-STD-001 {ver} &nbsp;·&nbsp; <a href="{pdf}">standard (PDF)</a> ·
  <a href="conformance.json">conformance record</a> ·
  <a href="https://github.com/fabriziosalmi/agssh">source</a> ·
  <a href="https://github.com/fabriziosalmi/agssh/blob/main/LICENSE">Apache-2.0</a>.
  Self-hosted, egress-free, and conformant — by construction.
</div></footer>
</body>
</html>
""".format(n=n_rules, f=n_fam, ver=ver, pdf=PDF_NAME, rules=rules_section(fams))

    os.makedirs(_site, exist_ok=True)
    with open(os.path.join(_site, "index.html"), "w") as f:
        f.write(doc)
    with open(os.path.join(_site, "agssh-std.css"), "w") as f:
        f.write(CSS)
    # Same-origin favicon (no /favicon.ico 404; CSP img-src 'self' allows it).
    with open(os.path.join(_site, "favicon.svg"), "w") as f:
        f.write(FAVICON)
    # Placeholders for the proof artifacts so the content deploy 404s nothing; the
    # publish-standard gate OVERWRITES these with the real scan-derived files
    # (badge.svg, the signed conformance.json, the syft SBOM) on its second deploy.
    # The placeholder badge makes NO tier claim — a Gold medal appears only once the
    # live scan actually earns it.
    for fn, body in [("badge.svg", PLACEHOLDER_BADGE),
                     ("conformance.json", PENDING_JSON % "conformance record"),
                     ("sbom.spdx.json", PENDING_JSON % "SBOM")]:
        p = os.path.join(_site, fn)
        if not os.path.exists(p):     # never clobber a real artifact the gate placed
            with open(p, "w") as f:
                f.write(body)
    pdf_src = os.path.join(_here, PDF_NAME)
    if os.path.exists(pdf_src):
        shutil.copy2(pdf_src, os.path.join(_site, PDF_NAME))
    # A CNAME so GitHub Pages serves the apex domain.
    with open(os.path.join(_site, "CNAME"), "w") as f:
        f.write("agssh.dev\n")
    print("site: %d rules, %d families -> %s (index.html, agssh-std.css, %s, CNAME)"
          % (n_rules, n_fam, os.path.relpath(_site, _here), PDF_NAME))


if __name__ == "__main__":
    build()
