// Code generated by standard/build_pdf.py from CHANGELOG.md — DO NOT EDIT.
// Regenerate: cd standard && python build_pdf.py

package rules

// StandardVersion is the AGSSH-STD-001 document version this build of the
// runner implements, derived from the newest CHANGELOG.md release heading.
const StandardVersion = "v1.3.2"
